# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        mongodb-version: ['5.0']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}   
        
    - name: Prepare cache
      uses: actions/cache@v2
      with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-        
        
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
   
    - name: Create env file
      run: |
          touch .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} > .env
          echo MONGODB_URL=${{ secrets.MONGODB }} >> .env
          echo ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} >> .env
          echo ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} >> .env
          echo ADMIN_PASSWORD_HASHED=${{ secrets.ADMIN_PASSWORD_HASHED }} >> .env
          echo ADMIN_ACCESS_TOKEN=${{ secrets.ADMIN_ACCESS_TOKEN }} >> .env
          
      
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: |
          node server/util/createAdminUser.js
          node server/server.js
          npx jest server/test/users.test.js
          npx jest server/test/cats.test.js 
        
